import React, { useState, useEffect } from 'react';
import './BlogStack.css';

const BlogStack = () => {
    const [activeIndex, setActiveIndex] = useState(0);
    const [isAutoPlay, setIsAutoPlay] = useState(true);

    const blogs = [
        {
            id: 1,
            title: "AI Predicts Next Unicorn Startups in Tech",
            summary: "Analysis reveals 5 startups showing exceptional growth patterns similar to early-stage unicorns.",
            aiConfidence: 92,
            category: "Market Analysis",
            timestamp: "2 hours ago",
            readTime: "4 min read",
            keyMetric: "85% growth potential",
            tags: ["AI", "Predictions", "Unicorn"]
        },
        {
            id: 2,
            title: "Risk Assessment: Web3 Startups in 2024",
            summary: "Deep dive into the risk factors affecting Web3 startups, with surprising stability indicators.",
            aiConfidence: 88,
            category: "Risk Analysis",
            timestamp: "5 hours ago",
            readTime: "6 min read",
            keyMetric: "65% success rate",
            tags: ["Web3", "Risk", "Trends"]
        },
        {
            id: 3,
            title: "Green Tech Startups: The Next Big Wave",
            summary: "Environmental technology sector shows promising investment opportunities with sustainable growth.",
            aiConfidence: 94,
            category: "Trend Prediction",
            timestamp: "8 hours ago",
            readTime: "5 min read",
            keyMetric: "78% market fit",
            tags: ["GreenTech", "Sustainable", "Growth"]
        },
        {
            id: 4,
            title: "AI Infrastructure: Hidden Gems",
            summary: "Identifying overlooked opportunities in AI infrastructure startups with solid fundamentals.",
            aiConfidence: 90,
            category: "Deep Analysis",
            timestamp: "12 hours ago",
            readTime: "7 min read",
            keyMetric: "92% tech advantage",
            tags: ["AI", "Infrastructure", "Innovation"]
        }
    ];

    useEffect(() => {
        let interval;
        if (isAutoPlay) {
            interval = setInterval(() => {
                setActiveIndex((current) => (current + 1) % blogs.length);
            }, 6000);
        }
        return () => clearInterval(interval);
    }, [isAutoPlay, blogs.length]);

    const handlePrevious = () => {
        setIsAutoPlay(false);
        setActiveIndex((current) => (current - 1 + blogs.length) % blogs.length);
    };

    const handleNext = () => {
        setIsAutoPlay(false);
        setActiveIndex((current) => (current + 1) % blogs.length);
    };

    const getCardStyle = (index) => {
        const diff = (index - activeIndex + blogs.length) % blogs.length;
        const translateZ = -diff * 50;
        const translateY = diff * 20;
        const rotateX = diff * -5;
        const opacity = Math.max(1 - diff * 0.2, 0.4);
        
        return {
            transform: `translateZ(${translateZ}px) translateY(${translateY}px) rotateX(${rotateX}deg)`,
            opacity,
            zIndex: blogs.length - diff
        };
    };

    return (
        <section className="blog-stack-section">
            <div className="section-content">
                <h2>AI Generated Insights</h2>
                <p className="section-description">
                    Real-time analysis and predictions generated by our AI agent
                </p>
                
                <div className="blog-stack-container"
                     onMouseEnter={() => setIsAutoPlay(false)}
                     onMouseLeave={() => setIsAutoPlay(true)}>
                    <button className="nav-btn prev-btn" onClick={handlePrevious}>
                        <span className="btn-glow"></span>
                        ↑
                    </button>
                    <button className="nav-btn next-btn" onClick={handleNext}>
                        <span className="btn-glow"></span>
                        ↓
                    </button>

                    {blogs.map((blog, index) => (
                        <div
                            key={blog.id}
                            className={`blog-card ${index === activeIndex ? 'active' : ''}`}
                            style={getCardStyle(index)}
                            onClick={() => setActiveIndex(index)}
                        >
                            <div className="card-content">
                                <div className="card-header">
                                    <span className="category">{blog.category}</span>
                                    <div className="ai-confidence">
                                        <span className="confidence-label">AI Confidence</span>
                                        <span className="confidence-score">{blog.aiConfidence}%</span>
                                    </div>
                                </div>
                                
                                <h3>{blog.title}</h3>
                                <p className="summary">{blog.summary}</p>

                                <div className="card-footer">
                                    <div className="metrics">
                                        <span className="key-metric">{blog.keyMetric}</span>
                                        <span className="timestamp">{blog.timestamp}</span>
                                    </div>
                                    <div className="tags">
                                        {blog.tags.map(tag => (
                                            <span key={tag} className="tag">{tag}</span>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default BlogStack; 